sudo: required
language: node_js
node_js:
#  - stable
  - 10
  - 9
  - 8

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - cp ormconfig.travis.json ormconfig.json

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
